# Generated by Django 5.2.3 on 2025-06-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('updated_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='PR001', max_length=100)),
                ('barcode_no', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('stock_in_hand', models.IntegerField(default=0, null=True)),
                ('order_threshold', models.CharField(max_length=18, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_in_hand_unit', to='ecom.units')),
            ],
        ),
    ]
