# Generated by Django 5.2.3 on 2025-06-29 11:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSaleMain',
            fields=[
                ('invoice_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('discount', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default=datetime.datetime(2025, 6, 29, 11, 38, 24, 495324, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StockSaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='ecom.products')),
                ('stock_sale_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_detail', to='ecom.stocksalemain')),
            ],
        ),
    ]
