# Generated by Django 5.2.3 on 2025-06-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_stocksalemain_alter_products_name_stocksaledetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocksaledetail',
            old_name='Product',
            new_name='product',
        ),
    ]
